### ISSUE TITLE
First time using the client side "oauth-ssh-token authorize" command fails

### ISSUE THREAD

**Issue by tscollins-nygc** [XSEDE/oauth-ssh#61]
I did the following per the documentation:

"# yum install python2-pip.noarch"
$ echo "PATH=${PATH}:~/.local/bin" >> ~/.bash_profile
$ echo "export PATH" >> ~/.bash_profile
$ .  ~/.bash_profile
$ pip install --user oauth-ssh

but when trying to generate/create/authorize a token:

[tscollins@tscollins-vm ~]$ oauth-ssh-token authorize ssh.tscwork.net
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "/nethome/tscollins/.local/bin/oauth-ssh-token", line 11, in <module>
    sys.exit(oauth_ssh_token())
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/oauth_ssh/oauth_ssh_token.py", line 88, in wrapper
    func(*args, **kw)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/oauth_ssh/oauth_ssh_token.py", line 124, in token_authorize
    policy = SSHService(fqdn, port).get_security_policy()
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/oauth_ssh/ssh_service.py", line 26, in get_security_policy
    transport = Transport(self._fqdn, self._port)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/oauth_ssh/transport.py", line 120, in __init__
    self.start_client(timeout=15)
  File "/nethome/tscollins/.local/lib/python2.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
AttributeError: Raw

and then login of course fails:

[tscollins@tscollins-vm ~]$ oauth-ssh tscollins@ssh.tscwork.net
No token found. Use `oauth-ssh-token authorize ssh.tscwork.net`.

**Comment by tscollins-nygc** [comment]
Made the changes and tried to connect from client:

[tscollins@tscollins-vm.nygenome.org Wed Aug 28 ~]$oauth-ssh ssh.tscwork.net
Could not determine remote account to use. Please use -l <account>.
[tscollins@tscollins-vm.nygenome.org Wed Aug 28 ~]$oauth-ssh -l tscollins ssh.tscwork.net
Unexpected reply from the SSH service:
[tscollins@tscollins-vm.nygenome.org Wed Aug 28 ~]$ssh -l tscollins ssh.tscwork.net
Enter your OAuth token:
Password:
Enter your OAuth token:

From the server:
cat /var/log/globusauth 
Aug 28 22:57:03 ssh systemd: Stopping System Logging Service...
Aug 28 22:57:03 ssh rsyslogd: [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="2565" x-info="http://www.rsyslog.com"] exiting on signal 15.
Aug 28 22:57:03 ssh systemd: Stopped System Logging Service.
Aug 28 22:57:03 ssh polkitd[710]: Unregistered Authentication Agent for unix-process:3247:8895855 (system bus name :1.1655, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Aug 28 22:57:42 ssh polkitd[710]: Registered Authentication Agent for unix-process:3270:8899737 (system bus name :1.1656 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Aug 28 22:57:42 ssh systemd: Starting System Logging Service...
Aug 28 22:57:42 ssh rsyslogd: [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="3276" x-info="http://www.rsyslog.com"] start
Aug 28 22:57:42 ssh polkitd[710]: Unregistered Authentication Agent for unix-process:3270:8899737 (system bus name :1.1656, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Aug 28 22:57:42 ssh systemd: Started System Logging Service.
Aug 28 22:58:01 ssh systemd: Created slice User Slice of pcp.
Aug 28 22:58:01 ssh systemd: Started Session 312 of user pcp.
Aug 28 22:58:01 ssh CROND[3292]: (pcp) CMD ( /usr/libexec/pcp/bin/pmie_check -C)
Aug 28 22:58:01 ssh systemd: Removed slice User Slice of pcp.
Aug 28 22:58:20 ssh sshd[3329]: fatal: input_userauth_info_response: wrong number of replies [preauth]
Aug 28 22:58:20 ssh dbus[736]: [system] Activating service name='org.fedoraproject.Setroubleshootd' (using servicehelper)
Aug 28 22:58:21 ssh dbus[736]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
Aug 28 22:58:21 ssh setroubleshoot: SELinux is preventing /usr/sbin/sshd from write access on the directory /etc/pki/nssdb. For complete SELinux messages run: sealert -l 07abde7e-68b1-4c66-98c2-53d42cee25cc
Aug 28 22:58:21 ssh python: SELinux is preventing /usr/sbin/sshd from write access on the directory /etc/pki/nssdb.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that sshd should be allowed write access on the nssdb directory by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'sshd' --raw | audit2allow -M my-sshd#012# semodule -i my-sshd.pp#012
Aug 28 22:58:47 ssh dbus[736]: [system] Activating service name='org.fedoraproject.Setroubleshootd' (using servicehelper)
Aug 28 22:58:48 ssh dbus[736]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
Aug 28 22:58:49 ssh setroubleshoot: SELinux is preventing /usr/sbin/sshd from write access on the directory /etc/pki/nssdb. For complete SELinux messages run: sealert -l 07abde7e-68b1-4c66-98c2-53d42cee25cc
Aug 28 22:58:49 ssh python: SELinux is preventing /usr/sbin/sshd from write access on the directory /etc/pki/nssdb.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that sshd should be allowed write access on the nssdb directory by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'sshd' --raw | audit2allow -M my-sshd#012# semodule -i my-sshd.pp#012
Aug 28 22:58:52 ssh sshd[3351]: error: PAM: Authentication failure for tscollins from vpn.nygenome.org
Aug 28 22:58:53 ssh sshd[3351]: Connection closed by 69.80.224.20 port 43826 [preauth]
Aug 28 22:59:27 ssh polkitd[710]: Registered Authentication Agent for unix-process:3383:8910197 (system bus name :1.1663 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
[root@ssh ~]#

**Comment by JasonAlt** [comment]
Two things stand out in that log:

1. selinux is preventing sshd from doing _something_ in `/etc/pki/nssdb`. I don't believe this is related but we can test it by disabling selinux `sudo setenforce 0` and trying oauth-ssh again.

2. And this error condition with I can not duplicate:
> fatal: input_userauth_info_response: wrong number of replies

Can you retry oauth-ssh with debug enabled to see if it logs this again to be sure this is related?

**Comment by tscollins-nygc** [comment]
@JasonAlt I built a new server instance in Google Compute, FQDN is ga-test.tscwork.net, and it seems to work now:
tscollins@tscollins-vm:~$ ssh -l oauth-ssh ga-test.tscwork.net
Enter your OAuth token: 

130 tscollins@tscollins-vm:~$ oauth-ssh-token authorize ga-test.tscwork.net
The authenticity of host 'ga-test.tscwork.net' can't be established.
ED25519 key fingerprint is SHA256:UlgGWFQMh2g0kpg/GaCAQ+7LYWSgcwRhs7QN7BYCpX4=
Are you sure you want to continue connecting (yes/no)? yes
Please go to this URL and login: https://auth.globus.org/v2/oauth2/authorize?code_challenge=_1eRtubYKCJiaQClZITt0_H7Wdt16fzSnW0Rf_aKag4&state=_default&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&code_challenge_method=S256&client_id=f8aa2b77-dafa-471d-af3b-5f5c6129eb82&scope=https%3A%2F%2Fauth.globus.org%2Fscopes%2Fga-test.tscwork.net%2Fssh&access_type=offline&response_type=code
Please enter the code you get after login here: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
1 tscollins@tscollins-vm:~$ oauth-ssh -l tscollins ga-test.tscwork.net
Last login: Thu Aug 29 20:38:52 2019 from 69.74.14.178
[tscollins@ga-test ~]$ id
uid=1001(tscollins) gid=1002(tscollins) groups=1002(tscollins),4(adm),39(video),1000(google-sudoers) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[tscollins@ga-test ~]$

**Comment by JasonAlt** [comment]
Good. Please report back if you figure out what was wrong with the configuration on the ec2 instance.
