### ISSUE TITLE
tag server releases

### ISSUE THREAD

**Issue by jbasney** [XSEDE/oauth-ssh#71]
I see a server release at http://software.xsede.org/development/repo/centos/7/x86_64/oauth-ssh-0.10-1.el7.x86_64.rpm but I can't find the corresponding release tag at https://github.com/XSEDE/oauth-ssh/releases or https://github.com/XSEDE/oauth-ssh/tags. Please tag releases.

**Comment by JasonAlt** [comment]
Server and client releases are now tagged.
