### ISSUE TITLE
Trying to setup oauth-ssh pam module with scitokens

### ISSUE THREAD

**Issue by sharper73** [XSEDE/oauth-ssh#76]
Hi, I've installed the oauth-ssh pam module and pulled in scitokens-cpp from EPEL, but I can't find the oauth-ssh.conf file anywhere.  I'm trying to get this running on CentOS 7, but the file the documentation mentions doesn't exist.   Can you point out where I'm going wrong?

Thanks,
Steve Harper
s.harper@utah.edu

**Comment by sharper73** [comment]
I tried to set this up registering things with Globus auth as the instructions describe, but now if I put in 
"https://auth.globus.org/v2/web/auth-code" as the redirect it says this redirect is only supported for native clients.  Then if you register it as a native client it does not allow you to obtain a client_id and a client_secret.  I guess there's a reason everyone is still using gsi-ssh.

Steve Harper

**Comment by JasonAlt** [comment]
Documentation updated in server/README.md on master to clear up how to fill out the redirect field and the corrected configuration file name.
