### ISSUE TITLE
valid non-native app redirect

### ISSUE THREAD

**Issue by dchaffin666** [XSEDE/oauth-ssh#77]
Works for me, except

In Server "App Registration", if Native App is unchecked according to the instructions, the following error message displays:
'https://auth.globus.org/v2/web/auth-code' is only allowed for native application clients

Globus docs seem to confirm this address is only for native apps https://docs.globus.org/api/auth/developer-guide/#register-app
Is there a valid redirect for ssh auth?

**Comment by JasonAlt** [comment]
Documentation updated in server/README.md on master to clear up how to fill out the redirect field.
